# Hemtt Documentation says this goes unused at the moment
name = "UAG Units"
# This will be added as a prefix to the PBO
# e.g UAGPMC_PBONAME
prefix = "uagpmc"

# Handles some sort of Version Handling, not quite sure what it does yet
[version]
major = 0
minor = 0
patch = 1

# This normally adds the Git Hash to the Version number
# 0 means to ignore which is used for when you are not using Git
git_hash = 0 # Default 8
