name = "UAG Servers"
prefix = "UAG_Servers"
mainprefix = "z"

[version]
major = 0
minor = 0
patch = 0
git_hash = 8

[properties]
author = "UAG Development Team"
url = "https://github.com/UnnamedArmaGroupHub/arma3"