name = "UAG URL Fetch"
prefix = "UAG_URL_Fetch"
mainprefix = "z"

[version]
major = 0
minor = 0
patch = 0
git_hash = 8

[files]
include = [
    "url_fetch.dll",
    "url_fetch_x64.dll",
]

[properties]
author = "UAG Development Team"
url = "https://github.com/uagpmc/arma3"